### ISSUE TITLE
SDSS data not in repo?

### ISSUE THREAD

**Issue by timothydmorton** [marius311/mpk_compilation#1]
Hi- The jupyter notebook accesses a file called `"dat/lrgdr7like/data/lrgdr7_ccmeasurements.txt"`, which doesn't appear to be in the repository.  Can this be added?  Thanks!

**Comment by marius311** [comment]
Hi Timothy, are running the notebook via the Docker container? If so, that file should be built into the container, are you not seeing it there for some reason?

**Comment by timothydmorton** [comment]
Ah no, I was looking to get the data files from the repo without using Docker.  Is this not possible?

**Comment by marius311** [comment]
You can look through the Dockerfile to see where various stuff is downloaded, that file in particular is coming from [here](https://github.com/marius311/mpk_compilation/blob/c93f86584f9bb10c0e1596488be1c6a95b8e2ed5/Dockerfile#L47). You could also always run the container and `docker cp` anything out of it that you needed. In terms of actually running the notebook, I'd definitely recommend to just use the container, but if you just need various data for other purposes this should work.

**Comment by timothydmorton** [comment]
Aha, ok great, thanks!
