### ISSUE TITLE
README should tell you how to export the final pdf

### ISSUE THREAD

**Issue by slosar** [marius311/mpk_compilation#2]
At the moment the final pdf is exported into internal docker filesystem and there is no easy way to get it out.
I could get it out by starting docker with something like
```
PORT=8888; docker run -v/home/anze/cosmo:/home/cosmo/notebooks/shared --rm -e PORT=$PORT -itp $PORT:$PORT marius311/mpk_compilation
```
and then outputing into `shared/plot.pdf` in the notebook, but I am unsure if this is how docker should be used.
(you can copy paste png out of the notebook, but for pdfs, I think you need to actually access the filesystem)

**Comment by slosar** [comment]
Actually, probably, if you want to edit the actual file, you should checkout git and then point docker to it!

**Comment by marius311** [comment]
Yea, exactly, use the second form

```
git clone https://github.com/marius311/mpk_compilation
cd mpk_compilation
docker-compose pull # or replace "pull" with "build" to build the image locally
PORT=8888 docker-compose up
```

which does that mount for you. But that is indeed the best way to do this kind of thing with Docker (technically `docker cp` is another way to get files in/out but mounting is easiest) 

I changed the readme to say this more clearly. Hope you find this useful and please do contribute back if you add any new datasets or make other imrovements!

**Comment by marius311** [comment]
The easier way, now mentioned in the readme: 

> Once you've run the notebook, if you want to download the figure in PDF format, return to the Jupyter notebook file screen (click the Jupyter logo), select the PDF file, and click download.
